services:
  app:
    restart: always
    environment:
      - MINIO_URL=http://${VPS_IP}:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - "8080:8080"

  minio:
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - minio_data:/data

  fastapi:
    restart: on-failure
    ports: []

  worker:
    restart: always
    environment:
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}

  nextjs:
    build:
      context: ./visum-front-end
      args:
        NEXT_PUBLIC_API_URL: http://${VPS_IP}:8080
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - app
    networks:
      - app_network

  redis:
    restart: always
    ports: []

volumes:
  minio_data: