spring:
  application:
    name: visum

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}

#server:
#  tomcat:
#    max-swallow-size: -1