spring:
  application:
    name: visum

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
    virtual-host: /

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: temp-audio
  region: us-east-1
